In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: LBCO, HRPT

This basic example is designed to show how Rietveld refinement can be
performed when both the crystal structure and experiment parameters
are defined using CIF files.

For this example, constant-wavelength neutron powder diffraction data
for La0.5Ba0.5CoO3 from HRPT at PSI is used.

The example is intended for users who are already familiar with the
EasyDiffraction library and want to quickly get started with a basic
refinement.

It is also useful for those who want to see how constraints can be
applied to highly correlated parameters. For a more detailed
explanation of the code, please refer to the other tutorials.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Define Project

In [3]:
# Create minimal project without name and description
project = ed.Project()

## Step 2: Define Crystal Structure

In [4]:
# Download CIF file from repository
structure_path = ed.download_data(id=1, destination='data')

Getting data...

Data #1: La0.5Ba0.5CoO3 (crystal structure)

✅ Data #1 downloaded to 'data/ed-1.cif'

In [5]:
# Add structure from downloaded CIF
project.structures.add_from_cif_path(structure_path)

## Step 3: Define Experiment

In [6]:
# Download CIF file from repository
expt_path = ed.download_data(id=2, destination='data')

Getting data...

Data #2: La0.5Ba0.5CoO3, HRPT (PSI), 300 K

✅ Data #2 downloaded to 'data/ed-2.cif'

In [7]:
# Add experiment from downloaded CIF
project.experiments.add_from_cif_path(expt_path)

## Step 4: Perform Analysis (no constraints)

In [8]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 138

✅ Fitting complete.

In [9]:
# Show fit results summary
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 11.30 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.25%

📏 Weighted R-factor (wR): 4.39%

📈 Fitted parameters:

red uncertainty — exceeds the fitted value (poorly constrained)

In [10]:
# Show parameter correlations
project.plotter.plot_param_correlations()

## Step 5: Perform Analysis (with constraints)

In [11]:
# As can be seen from the parameter-correlation plot, the isotropic
# displacement parameters of La and Ba are highly correlated. Because
# La and Ba share the same mixed-occupancy site, their contributions to
# the neutron diffraction pattern are difficult to separate, especially
# since their coherent scattering lengths are not very different.
# Therefore, it is necessary to constrain them to be equal. First we
# define aliases and then use them to create a constraint.
project.analysis.aliases.create(
    label='biso_La',
    param=project.structures['lbco'].atom_sites['La'].b_iso,
)
project.analysis.aliases.create(
    label='biso_Ba',
    param=project.structures['lbco'].atom_sites['Ba'].b_iso,
)
project.analysis.constraints.create(expression='biso_Ba = biso_La')

In [12]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 61

✅ Fitting complete.

In [13]:
# Show fit results summary
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 3.51 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.25%

📏 Weighted R-factor (wR): 4.39%

📈 Fitted parameters:

In [14]:
# Show parameter correlations
project.plotter.plot_param_correlations()

In [15]:
# Show defined experiment names
project.experiments.show_names()

Defined experiments 🔬

['hrpt']

In [16]:
# Plot measured vs. calculated diffraction patterns
project.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)