# Structure Refinement: Co2SiO4, D20 (Temperature scan)

This example demonstrates a Rietveld refinement of Co2SiO4 crystal
structure using constant wavelength neutron powder diffraction data
from D20 at ILL. A sequential refinement of the same structure against
a temperature scan is performed to show how to manage multiple
experiments in a project.

## Import Library

In [1]:
import easydiffraction as ed

## Step 1: Define Project

The project object is used to manage the structure, experiment, and
analysis.

In [2]:
# Create minimal project without name and description
project = ed.Project()

## Step 2: Define Crystal Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [3]:
project.structures.create(name='cosio')
structure = project.structures['cosio']

#### Set Space Group

In [4]:
structure.space_group.name_h_m = 'P n m a'
structure.space_group.it_coordinate_system_code = 'abc'

#### Set Unit Cell

In [5]:
structure.cell.length_a = 10.31
structure.cell.length_b = 6.0
structure.cell.length_c = 4.79

#### Set Atom Sites

In [6]:
structure.atom_sites.create(
    label='Co1',
    type_symbol='Co',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.3,
)
structure.atom_sites.create(
    label='Co2',
    type_symbol='Co',
    fract_x=0.279,
    fract_y=0.25,
    fract_z=0.985,
    wyckoff_letter='c',
    b_iso=0.3,
)
structure.atom_sites.create(
    label='Si',
    type_symbol='Si',
    fract_x=0.094,
    fract_y=0.25,
    fract_z=0.429,
    wyckoff_letter='c',
    b_iso=0.34,
)
structure.atom_sites.create(
    label='O1',
    type_symbol='O',
    fract_x=0.091,
    fract_y=0.25,
    fract_z=0.771,
    wyckoff_letter='c',
    b_iso=0.63,
)
structure.atom_sites.create(
    label='O2',
    type_symbol='O',
    fract_x=0.448,
    fract_y=0.25,
    fract_z=0.217,
    wyckoff_letter='c',
    b_iso=0.59,
)
structure.atom_sites.create(
    label='O3',
    type_symbol='O',
    fract_x=0.164,
    fract_y=0.032,
    fract_z=0.28,
    wyckoff_letter='d',
    b_iso=0.83,
)

## Define Experiment

This section shows how to add experiments, configure their parameters,
and link the structures defined in the previous step.

#### Download Measured Data

In [7]:
file_path = ed.download_data(id=26, destination='data')

Getting data...

Data #26: Co2SiO4, D20 (ILL), 57 files, T from ~50K to ~500K

✅ Data #26 downloaded to 'data/ed-26.zip'

#### Create Experiments and Set Temperature

In [8]:
data_paths = ed.extract_data_paths_from_zip(file_path)
for i, data_path in enumerate(data_paths, start=1):
    name = f'd20_{i}'
    project.experiments.add_from_data_path(
        name=name,
        data_path=data_path,
    )
    expt = project.experiments[name]
    expt.diffrn.ambient_temperature = ed.extract_metadata(
        file_path=data_path,
        pattern=r'^TEMP\s+([0-9.]+)',
    )

Data loaded successfully

Experiment 🔬 'd20_1'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_2'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_3'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_4'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_5'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_6'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_7'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_8'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_9'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_10'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_11'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_12'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_13'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_14'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_15'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_16'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_17'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_18'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_19'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_20'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_21'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_22'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_23'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_24'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_25'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_26'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_27'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_28'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_29'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_30'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_31'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_32'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_33'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_34'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_35'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_36'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_37'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_38'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_39'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_40'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_41'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_42'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_43'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_44'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_45'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_46'. Number of data points: 1507.

Data loaded successfully

Experiment 🔬 'd20_47'. Number of data points: 1507.

#### Set Instrument

In [9]:
for expt in project.experiments:
    expt.instrument.setup_wavelength = 1.87
    expt.instrument.calib_twotheta_offset = 0.29

#### Set Peak Profile

In [10]:
for expt in project.experiments:
    expt.peak.broad_gauss_u = 0.24
    expt.peak.broad_gauss_v = -0.53
    expt.peak.broad_gauss_w = 0.38
    expt.peak.broad_lorentz_y = 0.02

#### Set Excluded Regions

In [11]:
for expt in project.experiments:
    expt.excluded_regions.create(id='1', start=0, end=8)
    expt.excluded_regions.create(id='2', start=150, end=180)

#### Set Background

In [12]:
for expt in project.experiments:
    expt.background.create(id='1', x=8, y=609)
    expt.background.create(id='2', x=9, y=581)
    expt.background.create(id='3', x=10, y=563)
    expt.background.create(id='4', x=11, y=540)
    expt.background.create(id='5', x=12, y=520)
    expt.background.create(id='6', x=15, y=507)
    expt.background.create(id='7', x=25, y=463)
    expt.background.create(id='8', x=30, y=434)
    expt.background.create(id='9', x=50, y=451)
    expt.background.create(id='10', x=70, y=431)
    expt.background.create(id='11', x=90, y=414)
    expt.background.create(id='12', x=110, y=361)
    expt.background.create(id='13', x=130, y=292)
    expt.background.create(id='14', x=150, y=241)

#### Set Linked Phases

In [13]:
for expt in project.experiments:
    expt.linked_phases.create(id='cosio', scale=1.2)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Set Free Parameters

In [14]:
structure.cell.length_a.free = True
structure.cell.length_b.free = True
structure.cell.length_c.free = True

structure.atom_sites['Co2'].fract_x.free = True
structure.atom_sites['Co2'].fract_z.free = True
structure.atom_sites['Si'].fract_x.free = True
structure.atom_sites['Si'].fract_z.free = True
structure.atom_sites['O1'].fract_x.free = True
structure.atom_sites['O1'].fract_z.free = True
structure.atom_sites['O2'].fract_x.free = True
structure.atom_sites['O2'].fract_z.free = True
structure.atom_sites['O3'].fract_x.free = True
structure.atom_sites['O3'].fract_y.free = True
structure.atom_sites['O3'].fract_z.free = True

structure.atom_sites['Co1'].b_iso.free = True
structure.atom_sites['Co2'].b_iso.free = True
structure.atom_sites['Si'].b_iso.free = True
structure.atom_sites['O1'].b_iso.free = True
structure.atom_sites['O2'].b_iso.free = True
structure.atom_sites['O3'].b_iso.free = True

In [15]:
for expt in project.experiments:
    expt.linked_phases['cosio'].scale.free = True

    expt.instrument.calib_twotheta_offset.free = True

    expt.peak.broad_gauss_u.free = True
    expt.peak.broad_gauss_v.free = True
    expt.peak.broad_gauss_w.free = True
    expt.peak.broad_lorentz_y.free = True

    for point in expt.background:
        point.y.free = True

#### Set Constraints

Set aliases for parameters.

In [16]:
project.analysis.aliases.create(
    label='biso_Co1',
    param_uid=structure.atom_sites['Co1'].b_iso.uid,
)
project.analysis.aliases.create(
    label='biso_Co2',
    param_uid=structure.atom_sites['Co2'].b_iso.uid,
)

Set constraints.

In [17]:
project.analysis.constraints.create(
    expression='biso_Co2 = biso_Co1',
)

Apply constraints.

In [18]:
project.analysis.apply_constraints()

#### Set Fit Mode and Weights

In [19]:
project.analysis.fit_mode.mode = 'single'

#### Run Fitting

In [20]:
project.analysis.fit()

Using experiment 🔬 'd20_1' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.82 at iteration 323

✅ Fitting complete.

Using experiment 🔬 'd20_2' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.74 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_3' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.84 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_4' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.59 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_5' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.72 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_6' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.84 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_7' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.91 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_8' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.71 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_9' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.75 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_10' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.66 at iteration 203

✅ Fitting complete.

Using experiment 🔬 'd20_11' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.87 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_12' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.84 at iteration 172

✅ Fitting complete.

Using experiment 🔬 'd20_13' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.74 at iteration 203

✅ Fitting complete.

Using experiment 🔬 'd20_14' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.79 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_15' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.75 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_16' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.56 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_17' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.74 at iteration 127

✅ Fitting complete.

Using experiment 🔬 'd20_18' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.75 at iteration 140

✅ Fitting complete.

Using experiment 🔬 'd20_19' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.85 at iteration 187

✅ Fitting complete.

Using experiment 🔬 'd20_20' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.81 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_21' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.76 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_22' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.66 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_23' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.95 at iteration 243

✅ Fitting complete.

Using experiment 🔬 'd20_24' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.56 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_25' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.76 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_26' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.63 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_27' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.80 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_28' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.47 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_29' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.61 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_30' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.65 at iteration 243

✅ Fitting complete.

Using experiment 🔬 'd20_31' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.62 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_32' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.69 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_33' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.60 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_34' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.71 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_35' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.81 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_36' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.52 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_37' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.66 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_38' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.72 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_39' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.64 at iteration 203

✅ Fitting complete.

Using experiment 🔬 'd20_40' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.55 at iteration 243

✅ Fitting complete.

Using experiment 🔬 'd20_41' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.74 at iteration 203

✅ Fitting complete.

Using experiment 🔬 'd20_42' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.91 at iteration 163

✅ Fitting complete.

Using experiment 🔬 'd20_43' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.69 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_44' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.74 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_45' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.85 at iteration 283

✅ Fitting complete.

Using experiment 🔬 'd20_46' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.68 at iteration 203

✅ Fitting complete.

Using experiment 🔬 'd20_47' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.87 at iteration 283

✅ Fitting complete.

#### Plot Measured vs Calculated

In [21]:
last_expt_name = project.experiments.names[-1]
project.plot_meas_vs_calc(expt_name=last_expt_name, show_residual=True)

#### Plot parameters evolution

In [22]:
temperature = project.experiments[0].diffrn.ambient_temperature

In [23]:
project.plot_param_series(structure.cell.length_a, versus=temperature)
project.plot_param_series(structure.cell.length_b, versus=temperature)
project.plot_param_series(structure.cell.length_c, versus=temperature)

In [24]:
project.plot_param_series(structure.atom_sites['Co1'].b_iso, versus=temperature)
project.plot_param_series(structure.atom_sites['Si'].b_iso, versus=temperature)
project.plot_param_series(structure.atom_sites['O1'].b_iso, versus=temperature)
project.plot_param_series(structure.atom_sites['O2'].b_iso, versus=temperature)
project.plot_param_series(structure.atom_sites['O3'].b_iso, versus=temperature)