# Structure Refinement: Co2SiO4, D20

This example demonstrates a Rietveld refinement of Co2SiO4 crystal
structure using constant wavelength neutron powder diffraction data
from D20 at ILL.

## Import Library

In [1]:
from easydiffraction import ExperimentFactory
from easydiffraction import Project
from easydiffraction import StructureFactory
from easydiffraction import download_data

## Define Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [2]:
structure = StructureFactory.from_scratch(name='cosio')

#### Set Space Group

In [3]:
structure.space_group.name_h_m = 'P n m a'
structure.space_group.it_coordinate_system_code = 'abc'

#### Set Unit Cell

In [4]:
structure.cell.length_a = 10.3
structure.cell.length_b = 6.0
structure.cell.length_c = 4.8

#### Set Atom Sites

In [5]:
structure.atom_sites.create(
    label='Co1',
    type_symbol='Co',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='Co2',
    type_symbol='Co',
    fract_x=0.279,
    fract_y=0.25,
    fract_z=0.985,
    wyckoff_letter='c',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='Si',
    type_symbol='Si',
    fract_x=0.094,
    fract_y=0.25,
    fract_z=0.429,
    wyckoff_letter='c',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='O1',
    type_symbol='O',
    fract_x=0.091,
    fract_y=0.25,
    fract_z=0.771,
    wyckoff_letter='c',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='O2',
    type_symbol='O',
    fract_x=0.448,
    fract_y=0.25,
    fract_z=0.217,
    wyckoff_letter='c',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='O3',
    type_symbol='O',
    fract_x=0.164,
    fract_y=0.032,
    fract_z=0.28,
    wyckoff_letter='d',
    b_iso=0.5,
)

## Define Experiment

This section shows how to add experiments, configure their parameters,
and link the structures defined in the previous step.

#### Download Measured Data

In [6]:
data_path = download_data(id=12, destination='data')

Getting data...

Data #12: Co2SiO4, D20 (ILL)

✅ Data #12 downloaded to 'data/ed-12.xye'

#### Create Experiment

In [7]:
expt = ExperimentFactory.from_data_path(name='d20', data_path=data_path)

Data loaded successfully

Experiment 🔬 'd20'. Number of data points: 1418

#### Set Instrument

In [8]:
expt.instrument.setup_wavelength = 1.87
expt.instrument.calib_twotheta_offset = 0.1

#### Set Peak Profile

In [9]:
expt.peak.broad_gauss_u = 0.3
expt.peak.broad_gauss_v = -0.5
expt.peak.broad_gauss_w = 0.4

#### Set Background

In [10]:
expt.background.create(id='1', x=8, y=500)
expt.background.create(id='2', x=9, y=500)
expt.background.create(id='3', x=10, y=500)
expt.background.create(id='4', x=11, y=500)
expt.background.create(id='5', x=12, y=500)
expt.background.create(id='6', x=15, y=500)
expt.background.create(id='7', x=25, y=500)
expt.background.create(id='8', x=30, y=500)
expt.background.create(id='9', x=50, y=500)
expt.background.create(id='10', x=70, y=500)
expt.background.create(id='11', x=90, y=500)
expt.background.create(id='12', x=110, y=500)
expt.background.create(id='13', x=130, y=500)
expt.background.create(id='14', x=150, y=500)

#### Set Linked Phases

In [11]:
expt.linked_phases.create(id='cosio', scale=1.0)

## Define Project

The project object is used to manage the structure, experiment, and
analysis.

#### Create Project

In [12]:
project = Project()

#### Set Plotting Engine

In [13]:
# Keep the auto-selected engine. Alternatively, you can uncomment the
# line below to explicitly set the engine to the required one.
# project.plotter.engine = 'plotly'

#### Add Structure

In [14]:
project.structures.add(structure)

#### Add Experiment

In [15]:
project.experiments.add(expt)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Set Minimizer

In [16]:
project.analysis.current_minimizer = 'lmfit'

Current minimizer changed to

lmfit

#### Plot Measured vs Calculated

In [17]:
project.plot_meas_vs_calc(expt_name='d20', show_residual=True)

In [18]:
project.plot_meas_vs_calc(expt_name='d20', x_min=41, x_max=54, show_residual=True)

#### Set Free Parameters

In [19]:
structure.cell.length_a.free = True
structure.cell.length_b.free = True
structure.cell.length_c.free = True

structure.atom_sites['Co2'].fract_x.free = True
structure.atom_sites['Co2'].fract_z.free = True
structure.atom_sites['Si'].fract_x.free = True
structure.atom_sites['Si'].fract_z.free = True
structure.atom_sites['O1'].fract_x.free = True
structure.atom_sites['O1'].fract_z.free = True
structure.atom_sites['O2'].fract_x.free = True
structure.atom_sites['O2'].fract_z.free = True
structure.atom_sites['O3'].fract_x.free = True
structure.atom_sites['O3'].fract_y.free = True
structure.atom_sites['O3'].fract_z.free = True

structure.atom_sites['Co1'].b_iso.free = True
structure.atom_sites['Co2'].b_iso.free = True
structure.atom_sites['Si'].b_iso.free = True
structure.atom_sites['O1'].b_iso.free = True
structure.atom_sites['O2'].b_iso.free = True
structure.atom_sites['O3'].b_iso.free = True

In [20]:
expt.linked_phases['cosio'].scale.free = True

expt.instrument.calib_twotheta_offset.free = True

expt.peak.broad_gauss_u.free = True
expt.peak.broad_gauss_v.free = True
expt.peak.broad_gauss_w.free = True
expt.peak.broad_lorentz_y.free = True

for point in expt.background:
    point.y.free = True

#### Set Constraints

Set aliases for parameters.

In [21]:
project.analysis.aliases.create(
    label='biso_Co1',
    param_uid=project.structures['cosio'].atom_sites['Co1'].b_iso.uid,
)
project.analysis.aliases.create(
    label='biso_Co2',
    param_uid=project.structures['cosio'].atom_sites['Co2'].b_iso.uid,
)

Set constraints.

In [22]:
project.analysis.constraints.create(
    lhs_alias='biso_Co2',
    rhs_expr='biso_Co1',
)

Apply constraints.

In [23]:
project.analysis.apply_constraints()

#### Run Fitting

In [24]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'd20' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.373383617544757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.373383617544757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.3733873514182712 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877388699893504 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877388699893504 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -1.0877497474868254 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763660916558077 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763660916558077 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.6763728553843615 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851147026990017 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851147026990017 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.5851205539045408 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896368488567395 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896368488567395 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.37896747456041957 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133564878417413 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133564878417413 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.15133716215579568 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.09524996181237429 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.09524996181237429 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0952509143215175 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954803009883357 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954803009883357 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08954892558808945 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08840134742816119 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08840134742816119 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.0884022314504757 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806831241952466 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806831241952466 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08806919311145578 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.

🏆 Best goodness-of-fit (reduced χ²) is 4.58 at iteration 483

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 26.12 seconds

📏 Goodness-of-fit (reduced χ²): 4.58

📏 R-factor (Rf): 3.05%

📏 R-factor squared (Rf²): 4.46%

📏 Weighted R-factor (wR): 4.74%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [25]:
project.plot_meas_vs_calc(expt_name='d20', show_residual=True)

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.

In [26]:
project.plot_meas_vs_calc(expt_name='d20', x_min=41, x_max=54, show_residual=True)

Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.
Failed to apply constraint 'biso_Co2 = biso_Co1': Value mismatch for <cosio.atom_site.Co2.b_iso>. Provided -0.08796141260596217 outside [0.0, inf]. Keeping current 0.08838381672996182.

## Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [27]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

Untitled Project

—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 cosio

Space group

P n m a

Cell parameters

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 d20

Experiment type

powder, neutron, constant wavelength

Wavelength

1.87000

2θ offset

0.28845

Profile type

PeakProfileTypeEnum.PSEUDO_VOIGT

Peak broadening (Gaussian)

Peak broadening (Lorentzian)

———————
FITTING
———————

Calculation engine

  d20: CalculatorEnum.CRYSPY

Minimization engine

lmfit

Fit quality